# Generated by Django 4.0.6 on 2023-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Famale')], default='male', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mode',
            field=models.CharField(choices=[('kid', 'kid'), ('teenager', 'teenager'), ('adult', 'adult'), ('alder', 'alder')], default='kid', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'user')], default='user', max_length=10),
        ),
    ]
