# Generated by Django 4.0.6 on 2023-06-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_alter_post_video_userprofile_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
