# Generated by Django 4.0.6 on 2023-06-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_friendrequest_friendlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='mode',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('declined', 'declined')], default='pending', max_length=10),
        ),
    ]
