# Generated by Django 4.0.6 on 2023-07-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('root', '0009_alter_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=900)),
                ('price', models.IntegerField()),
                ('owner_type', models.CharField(max_length=20)),
                ('pic1', models.ImageField(upload_to='photos/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
